// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rules.Data;

namespace Rules.Data.Migrations
{
    [DbContext(typeof(RulesContext))]
    [Migration("20200817194743_rules_changeRulesParameter1_migration")]
    partial class rules_changeRulesParameter1_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rules.Data.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("LoanProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRuleId")
                        .HasColumnType("int");

                    b.Property<string>("ValueToCompeare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRuleId");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("Rules.Data.Entities.RulesParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RulesParameters");
                });

            modelBuilder.Entity("Rules.Data.Entities.Rule", b =>
                {
                    b.HasOne("Rules.Data.Entities.Rule", "ParentRule")
                        .WithMany("ChildrenRules")
                        .HasForeignKey("ParentRuleId");
                });
#pragma warning restore 612, 618
        }
    }
}
